// Generated by gencpp from file projection/serviceRequest.msg
// DO NOT EDIT!


#ifndef PROJECTION_MESSAGE_SERVICEREQUEST_H
#define PROJECTION_MESSAGE_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace projection
{
template <class ContainerAllocator>
struct serviceRequest_
{
  typedef serviceRequest_<ContainerAllocator> Type;

  serviceRequest_()
    : L()  {
    }
  serviceRequest_(const ContainerAllocator& _alloc)
    : L(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _L_type;
  _L_type L;




  typedef boost::shared_ptr< ::projection::serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::projection::serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct serviceRequest_

typedef ::projection::serviceRequest_<std::allocator<void> > serviceRequest;

typedef boost::shared_ptr< ::projection::serviceRequest > serviceRequestPtr;
typedef boost::shared_ptr< ::projection::serviceRequest const> serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::projection::serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::projection::serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace projection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::projection::serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::projection::serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projection::serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::projection::serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projection::serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::projection::serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::projection::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c2cc25d6004da2681799b24f2e02ab6";
  }

  static const char* value(const ::projection::serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c2cc25d6004da26ULL;
  static const uint64_t static_value2 = 0x81799b24f2e02ab6ULL;
};

template<class ContainerAllocator>
struct DataType< ::projection::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "projection/serviceRequest";
  }

  static const char* value(const ::projection::serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::projection::serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] L\n\
";
  }

  static const char* value(const ::projection::serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::projection::serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.L);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::projection::serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::projection::serviceRequest_<ContainerAllocator>& v)
  {
    s << indent << "L[]" << std::endl;
    for (size_t i = 0; i < v.L.size(); ++i)
    {
      s << indent << "  L[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.L[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECTION_MESSAGE_SERVICEREQUEST_H
